background #0a0a0a
foreground #c8c8c8
cursor #c8c8c8
selection_background #333333
selection_foreground #f5f5f5

color0  #0a0a0a
color1  #262626
color2  #363636
color3  #4a4a4a
color4  #6a6a6a
color5  #8a8a8a
color6  #aaaaaa
color7  #c8c8c8

color8  #555555
color9  #777777
color10 #999999
color11 #bbbbbb
color12 #cccccc
color13 #dddddd
color14 #eeeeee
color15 #f5f5f5
