#!/usr/bin/env bash
if [ -z "$DBUS_SESSION_BUS_ADDRESS" ]; then
    eval "$(dbus-launch --sh-syntax)"
fi

if ! pgrep -x pipewire >/dev/null 2>&1; then
    pipewire &
    pipewire-pulse &
    wireplumber &
fi

(sleep 2 && xset r rate 200 35 && xset m 0/1 4) &
xrandr --output HDMI-A-0 --pos 1920x67 --auto &
xinput set-prop "ATK NK mouse NANO dongle" "libinput Accel Profile Enabled" 0 1 0 &
xwallpaper --output DisplayPort-2 --maximize ~/Downloads/wp12478763-monochrome-4k-wallpapers.jpg --output HDMI-A-0 --center ~/Pictures/bruh2/Black.png &
fcitx5 -d &
xset -dpms &
xset s off &
xset s noblank &
